url: https://goralexcomp.github.io/OnePage/

plugins:
  - jekyll-multiple-languages-plugin
languages: ["uk", "en"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: uk
languageNames:
  uk: Українська
  en: English