url: https://goralexcomp.github.io/OnePage/
baseurl: https://goralexcomp.github.io/OnePage/

languages: ["uk", "en"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: uk
languageNames:
  uk: Українська
  en: English